### ISSUE TITLE
Sub operation produces bad result for specific case

### ISSUE THREAD

**Issue by adamborowski** [exjs/qintervals#1]
Hello,
consider the case
```
var d = [2, 3, 5, 6, 8, 11];
var e = [2, 11, 12, 13];
expect(qintervals.sub(d, e).data).to.be.empty;
```
Unfortunately, it produces 
```
[8,11]
```
instead of empty array.

Let me visualize this:
```
     ┏ 2  ┓
     ┃    ┃
     ┗ 3  ┃
     ┏ 5  ┃
     ┃    ┃
     ┗ 6  ┃
     ┏ 8  ┃
     ┃    ┃
     ┗ 11 ┛
       12 ┓
          ┃
       13 ┛
```
Note that for slightly different data, it works.
```javascript
var d = [2, 3, /*5, 6,*/ 8, 11];
var e = [2, 11, 12, 13];
```

**Comment by adamborowski** [comment]
a workaround for this is to repeat sub operation like:
```
expect(qintervals.sub(d, e).sub(e).data).to.be.empty;
```

**Comment by kobalicek** [comment]
Thanks, it's a bug that I'm gonna fix

**Comment by kobalicek** [comment]
I took a look and it should be fixed, however, you have to `pull --force` as I messed the commit a bit.

**Comment by adamborowski** [comment]
How it applies to npm registry? I use it that way.

**Comment by kobalicek** [comment]
I was in a process of renaming some packages, `qintervals` is now available as `xspans`, which contains this fix. Thanks for understanding :)
